//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    
    public partial class BalanceReportItem
    {
        public int OfficeID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Income { get; set; }
        public Nullable<double> Expense { get; set; }
        public Nullable<double> CashCollection { get; set; }
        public Nullable<double> Balance { get; set; }
        public double InternalCashCollection { get; set; }
    }
}
