//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarPeriod
    {
        public int ID { get; set; }
        public int TranslatorID { get; set; }
        public byte StatusCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public string StaffStatus { get; set; }
        public int OfficeID { get; set; }
        public bool StandBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatorID { get; set; }
        public bool Confirmed { get; set; }
        public StaffStatuses StaffStatusID { get; set; }
    
        public virtual Translator Translator { get; set; }
        public virtual Office Office { get; set; }
        public virtual Translator Creator { get; set; }
        public virtual StaffStatus StaffStatusEntity { get; set; }
    }
}
