//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAndStatusChangeReportItem
    {
        public int ID { get; set; }
        public string JobID { get; set; }
        public string JobName { get; set; }
        public string CalleeName { get; set; }
        public string ContactResult { get; set; }
        public string Status { get; set; }
        public string StatusComment { get; set; }
        public Nullable<System.DateTime> StatusEndDate { get; set; }
        public string Caller { get; set; }
        public string Office { get; set; }
        public System.DateTime ContactDate { get; set; }
    }
}
