//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string CustomerCode { get; set; }
        public string CurrentContractName { get; set; }
        public Nullable<System.DateTime> CurrentContractExpiryDate { get; set; }
        public string LegalAddress { get; set; }
        public string ActualAddress { get; set; }
        public string VATNo { get; set; }
        public string KPP { get; set; }
        public string Bank { get; set; }
        public string BIC { get; set; }
        public string SettlementAccount { get; set; }
        public string CorrespondentAccount { get; set; }
        public string Comment { get; set; }
        public string PriceName { get; set; }
        public string z_ch { get; set; }
        public Nullable<int> BranchOrCustomer { get; set; }
        public string Source { get; set; }
        public string ActivityType { get; set; }
        public string BranchOfEconomy { get; set; }
        public Nullable<System.DateTime> Izm { get; set; }
        public int LegalEntity { get; set; }
        public int BranchID { get; set; }
        public string pod_nic { get; set; }
        public int klas { get; set; }
        public int MarketingClassification { get; set; }
        public string Site { get; set; }
        public string Metro { get; set; }
        public int Tax { get; set; }
        public string Manager { get; set; }
        public string DefaultPath { get; set; }
        public Nullable<int> InternalCustomerOfficeID { get; set; }
        public int IsDeleted { get; set; }
        public int z_rnd { get; set; }
        public int AttractionChannelID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool is_imported { get; set; }
        public bool is_individual { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual MarketingClass MarketingClass { get; set; }
        public virtual AttractionChannel AttractionChannel { get; set; }
    }
}
