//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditorialComment
    {
        public string ID { get; set; }
        public Nullable<int> rd_nn { get; set; }
        public string JobID { get; set; }
        public Nullable<int> TranslatorID { get; set; }
        public string TranslatorName { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
    
        public virtual Translator Translator { get; set; }
        public virtual Job Job { get; set; }
    }
}
