//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalDomain
    {
        public int IntDomainID { get; set; }
        public Nullable<int> TranslatorID { get; set; }
        public int LanguageID { get; set; }
        public string pl_vid { get; set; }
        public string QA { get; set; }
        public Nullable<int> DomainID { get; set; }
        public Nullable<int> Competence { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public bool is_del { get; set; }
    
        public virtual TranslationDirection TranslationDirection { get; set; }
        public virtual Domain Domain { get; set; }
        public virtual Translator Translator { get; set; }
        public virtual Translator Perevod1 { get; set; }
        public virtual Translator Perevod2 { get; set; }
    }
}
