//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.JobParticipants = new HashSet<JobParticipant>();
            this.JobFiles = new HashSet<JobFile>();
            this.EditorialComments = new HashSet<EditorialComment>();
        }
    
        public string ID { get; set; }
        public Nullable<int> r_nn { get; set; }
        public string r_nic { get; set; }
        public Nullable<int> r_num { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> PlannedCompletionDate { get; set; }
        public Nullable<System.DateTime> TakeUpDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<System.DateTime> SentToCustomerDate { get; set; }
        public Nullable<int> JobStatusID { get; set; }
        public Nullable<int> JobParticipantsMaxStatusID { get; set; }
        public Nullable<int> AccountingStatusID { get; set; }
        public Nullable<int> JobTypeID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CharCount { get; set; }
        public Nullable<double> PagesCount { get; set; }
        public Nullable<int> CharCountWithSpaces { get; set; }
        public Nullable<double> PagesCountWithSpaces { get; set; }
        public Nullable<int> FinalCharCount { get; set; }
        public Nullable<double> FinalPagesCount { get; set; }
        public Nullable<int> FinalCharCountWithSpaces { get; set; }
        public Nullable<double> FinalPagesCountWithSpaces { get; set; }
        public Nullable<double> FinalPagesCountForCustomer { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> AmountAtJobCreate { get; set; }
        public Nullable<double> AmountCash { get; set; }
        public Nullable<double> AmountFinal { get; set; }
        public string Comment { get; set; }
        public string InvoiceOrCashPaymentInfoString { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> InvoicePaidDate { get; set; }
        public string TranslatorInfoString { get; set; }
        public string PaymentMethodString { get; set; }
        public string SpecificationNumberString { get; set; }
        public Nullable<System.DateTime> SpecificationDate { get; set; }
        public string DocumentString { get; set; }
        public string EditorString { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> OMKRequestStatusID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Domain1 { get; set; }
        public Nullable<int> Domain2 { get; set; }
        public string Notarized { get; set; }
        public string OCRRequested { get; set; }
        public string AnalysisRequested { get; set; }
        public string TermsRequired { get; set; }
        public string PretransRequired { get; set; }
        public Nullable<int> OCRRequestStatusID { get; set; }
        public Nullable<int> AnalysisRequestStatusID { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string ContactMail { get; set; }
        public string Publication { get; set; }
        public string an_1 { get; set; }
        public string an_2 { get; set; }
        public string an_3 { get; set; }
        public string an_4 { get; set; }
        public string an_5 { get; set; }
        public string an_6 { get; set; }
        public string an_7 { get; set; }
        public string AdditionalNumber { get; set; }
        public string Contract { get; set; }
        public string MainParticipantID { get; set; }
        public string ParentOfficeName { get; set; }
        public string ParentManagerName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<System.DateTime> OCRDatePlanned { get; set; }
        public Nullable<System.DateTime> OCRDateActual { get; set; }
        public string OCRDoneBy { get; set; }
        public Nullable<double> PagesOCR { get; set; }
        public string FilePath { get; set; }
        public string AccountingRecordID { get; set; }
        public Nullable<System.DateTime> DateForEditor { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> DiscountedAmount { get; set; }
        public int SpecificationStatus { get; set; }
        public int AttractionChannelID { get; set; }
        public string explanation { get; set; }
    
        public virtual ICollection<JobParticipant> JobParticipants { get; set; }
        public virtual ICollection<JobFile> JobFiles { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual Language LanguageDirection { get; set; }
        public virtual Domain MainDomain { get; set; }
        public virtual Domain SecondaryDomain { get; set; }
        public virtual JobStatus JobStatus { get; set; }
        public virtual JobParticipantStatus JobParticipantsMaxStatus { get; set; }
        public virtual AccountingStatus AccountingStatus { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Office Office { get; set; }
        public virtual OMKRequestStatus OMKRequest { get; set; }
        public virtual OCRRequestStatus OCRRequest { get; set; }
        public virtual OMKRequestStatus AnalysisRequestStatus { get; set; }
        public virtual JobParticipant MainJobParticipant { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<EditorialComment> EditorialComments { get; set; }
        public virtual AttractionChannel AttractionChannel { get; set; }
    }
}
