//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobFile
    {
        public string ID { get; set; }
        public Nullable<int> rr_nn { get; set; }
        public string JobID { get; set; }
        public Nullable<int> TranslatorID { get; set; }
        public Nullable<int> Status { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CharCount { get; set; }
        public Nullable<int> CharCountWithSpaces { get; set; }
        public Nullable<double> PagesCount { get; set; }
        public Nullable<double> PagesCountWithSpaces { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public string an_1 { get; set; }
        public string an_2 { get; set; }
        public string an_3 { get; set; }
        public string an_4 { get; set; }
        public string an_5 { get; set; }
        public string an_6 { get; set; }
        public string ParticipantID { get; set; }
        public string Perev { get; set; }
    
        public virtual Translator Translator { get; set; }
        public virtual JobParticipant JobParticipant { get; set; }
        public virtual Job Job { get; set; }
    }
}
