//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobGrade
    {
        public int ID { get; set; }
        public string ParticipantID { get; set; }
        public int TranslatorID { get; set; }
        public Nullable<int> Spelling { get; set; }
        public Nullable<int> Fact { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Grammar { get; set; }
        public Nullable<int> Sense { get; set; }
        public Nullable<int> Gaps { get; set; }
        public Nullable<int> Requirements { get; set; }
        public Nullable<int> Style { get; set; }
        public Nullable<int> Delay { get; set; }
        public Nullable<int> FormatError { get; set; }
        public Nullable<int> BonusForQuality { get; set; }
        public Nullable<int> BonusToNative { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<System.DateTime> GradeDate { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Comment { get; set; }
        public string LegacyDirection { get; set; }
        public string LegacyDomain1 { get; set; }
        public string LegacyDomain2 { get; set; }
        public string LegacyJobNo { get; set; }
    
        public virtual Translator Translator { get; set; }
    }
}
