//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobParticipant
    {
        public JobParticipant()
        {
            this.JobFiles = new HashSet<JobFile>();
            this.DaughterJobs = new HashSet<Job>();
        }
    
        public string ID { get; set; }
        public Nullable<int> pr_nn { get; set; }
        public Nullable<int> TranslatorID { get; set; }
        public string JobID { get; set; }
        public string JobName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CharCount { get; set; }
        public Nullable<int> FinalCharCount { get; set; }
        public Nullable<double> PagesCount { get; set; }
        public Nullable<double> FinalPagesCount { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<double> FinalAmount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> EditStartDate { get; set; }
        public Nullable<System.DateTime> dt_verst_st { get; set; }
        public Nullable<System.DateTime> ComletionDateActual { get; set; }
        public Nullable<System.DateTime> EditEndDate { get; set; }
        public Nullable<System.DateTime> dt_verst_fn { get; set; }
        public Nullable<int> Title { get; set; }
        public Nullable<int> TitleStatusID { get; set; }
        public Nullable<double> Category { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> dt_opl { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> CharCountWithSpaces { get; set; }
        public Nullable<int> FinalCharCountWithSpaces { get; set; }
        public Nullable<double> PageCountWithSpaces { get; set; }
        public Nullable<double> FinalPageCountWithSpacs { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> JobTypeID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> PaymentBasis { get; set; }
        public Nullable<int> EditorApprovalStatusID { get; set; }
        public string Approver { get; set; }
        public Nullable<int> Main { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int p_check { get; set; }
        public Nullable<bool> OCR { get; set; }
        public string kom { get; set; }
    
        public virtual Translator Translator { get; set; }
        public virtual Job Job { get; set; }
        public virtual ICollection<JobFile> JobFiles { get; set; }
        public virtual Language LanguageDirection { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual JobParticipantStatus JobParticipantStatus { get; set; }
        public virtual ICollection<Job> DaughterJobs { get; set; }
    }
}
