//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Jobs = new HashSet<Job>();
            this.JobParticipants = new HashSet<JobParticipant>();
            this.TranslationDirection = new HashSet<TranslationDirection>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> grp { get; set; }
        public string k_ch { get; set; }
        public string k_full { get; set; }
        public string k_iso { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<JobParticipant> JobParticipants { get; set; }
        public virtual ICollection<TranslationDirection> TranslationDirection { get; set; }
    }
}
