//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.Translators = new HashSet<Translator>();
            this.Tickets = new HashSet<Ticket>();
            this.TranslatorReference = new HashSet<Translator>();
            this.CalendarPeriods = new HashSet<CalendarPeriod>();
            this.Jobs = new HashSet<Job>();
            this.TicketTypes = new HashSet<TicketType>();
            this.PaymentInfoes = new HashSet<PaymentInfo>();
        }
    
        public int ID { get; set; }
        public Nullable<int> pod_ur { get; set; }
        public string Name { get; set; }
        public Nullable<int> pod_rod { get; set; }
        public string pod_ch { get; set; }
        public Nullable<int> pod_kop { get; set; }
        public Nullable<int> pod_aop { get; set; }
        public Nullable<int> pod_zav { get; set; }
        public Nullable<int> pod_per { get; set; }
        public string pod_nic { get; set; }
        public Nullable<int> pod_avt { get; set; }
        public string OfficialName { get; set; }
        public string pod_dir { get; set; }
        public int Del { get; set; }
        public bool IsSalesOffice { get; set; }
        public bool IsInHouseOffice { get; set; }
    
        public virtual ICollection<Translator> Translators { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<Translator> TranslatorReference { get; set; }
        public virtual ICollection<CalendarPeriod> CalendarPeriods { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<TicketType> TicketTypes { get; set; }
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
    }
}
