//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    
    public partial class OrphanGradesResult
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public string Domain { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> GradeDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Grade { get; set; }
        public string JobName { get; set; }
        public Nullable<int> PreviousJobsCount { get; set; }
        public Nullable<int> PreviousGradesCount { get; set; }
    }
}
