//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentItemType
    {
        public PaymentItemType()
        {
            this.ChildItems = new HashSet<PaymentItemType>();
            this.PaymentInfos = new HashSet<PaymentInfo>();
        }
    
        public string Name { get; set; }
        public bool IsExpenseItem { get; set; }
        public Nullable<int> ParentItemID { get; set; }
        public int ID { get; set; }
        public bool IsCashCollection { get; set; }
    
        public virtual ICollection<PaymentItemType> ChildItems { get; set; }
        public virtual PaymentItemType ParentItem { get; set; }
        public virtual ICollection<PaymentInfo> PaymentInfos { get; set; }
    }
}
