//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            this.PaymentItems = new HashSet<PaymentInfo>();
        }
    
        public string Name { get; set; }
        public string o_ch { get; set; }
        public bool IsCashPayment { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<PaymentInfo> PaymentItems { get; set; }
        public virtual PaymentMethod Spo_Opl1 { get; set; }
        public virtual PaymentMethod Spo_Opl2 { get; set; }
    }
}
