//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfo
    {
        public int ID { get; set; }
        public int TranslatorID { get; set; }
        public Nullable<int> Principal { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string ICQ { get; set; }
        public string Skype { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public bool healed { get; set; }
        public string tel_ext { get; set; }
    
        public virtual Translator Translator { get; set; }
    }
}
