//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    
    public enum StaffStatuses : int
    {
        Present = 2,
        Remote = 3,
        Holiday = 4,
        PaidSingleDayHoliday = 5,
        PaidLongHolidgay = 6,
        NonPaidHoliday = 7,
        Skip = 8,
        Sick = 9,
        BusinessTrip = 10,
        Fired = 11,
        NotWorking = 1
    }
}
