//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffStatus
    {
        public StaffStatus()
        {
            this.CalendarPeriods = new HashSet<CalendarPeriod>();
        }
    
        public StaffStatuses ID { get; set; }
        public string ShortCode { get; set; }
        public string Name { get; set; }
        public int BusyStatusID { get; set; }
        public bool IsPaid { get; set; }
    
        public virtual ICollection<CalendarPeriod> CalendarPeriods { get; set; }
    }
}
