//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tema_active
    {
        public int t_id { get; set; }
        public string t_name { get; set; }
        public Nullable<int> t_rod { get; set; }
        public string t_ch { get; set; }
        public Nullable<int> t_kat { get; set; }
        public string description { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public bool is_del { get; set; }
    }
}
