//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketComment
    {
        public int ID { get; set; }
        public int AuthorID { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CommentDate { get; set; }
        public int TicketID { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual Translator Author { get; set; }
    }
}
