//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketStatus
    {
        public TicketStatus()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string name_description { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual TicketStatus ticketstatuses1 { get; set; }
        public virtual TicketStatus ticketstatuses2 { get; set; }
    }
}
