//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translator
    {
        public Translator()
        {
            this.CreatedTickets = new HashSet<Ticket>();
            this.AssignedTickets = new HashSet<Ticket>();
            this.ChangedTickets = new HashSet<Ticket>();
            this.PersonalInfos = new HashSet<PersonalInfo>();
            this.TicketComments = new HashSet<TicketComment>();
            this.CalendarPeriods = new HashSet<CalendarPeriod>();
            this.JobParticipants = new HashSet<JobParticipant>();
            this.Files = new HashSet<JobFile>();
            this.EditorialComments = new HashSet<EditorialComment>();
            this.TranslatorRoles = new HashSet<TranslatorRole>();
            this.TranslationDirections = new HashSet<TranslationDirection>();
            this.Domains = new HashSet<InternalDomain>();
            this.tickets3 = new HashSet<Ticket>();
            this.tickets4 = new HashSet<Ticket>();
            this.CalenardPeriodsCreated = new HashSet<CalendarPeriod>();
            this.Grades = new HashSet<JobGrade>();
            this.Per_Tem1 = new HashSet<InternalDomain>();
            this.Per_Tem2 = new HashSet<InternalDomain>();
            this.Temas = new HashSet<Domain>();
            this.Temas1 = new HashSet<Domain>();
            this.Rab_buh = new HashSet<PaymentInfo>();
            this.Rab_buh1 = new HashSet<PaymentInfo>();
        }
    
        public int TranslatorID { get; set; }
        public Nullable<int> r_mm { get; set; }
        public string Name { get; set; }
        public string v_name { get; set; }
        public string yazuk { get; set; }
        public Nullable<int> TitleID { get; set; }
        public Nullable<int> TitleStatusID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> CurrentStatusID { get; set; }
        public Nullable<System.DateTime> StatusValidThrough { get; set; }
        public string StatusComment { get; set; }
        public string serv { get; set; }
        public string Adres { get; set; }
        public string Gorod { get; set; }
        public string msk { get; set; }
        public string Raschet { get; set; }
        public string Rekv { get; set; }
        public string po { get; set; }
        public Nullable<System.DateTime> Dt_Rod { get; set; }
        public string staj { get; set; }
        public string rezume { get; set; }
        public string p_rezume_file { get; set; }
        public string Ip { get; set; }
        public string Login { get; set; }
        public string PSW { get; set; }
        public Nullable<System.DateTime> Izm { get; set; }
        public Nullable<int> r_mt { get; set; }
        public Nullable<int> r_ml { get; set; }
        public string noch { get; set; }
        public string vuhod { get; set; }
        public string verst { get; set; }
        public string active { get; set; }
        public string spec { get; set; }
        public string valute { get; set; }
        public string dop { get; set; }
        public string Izm_Isp { get; set; }
        public Nullable<double> QA { get; set; }
        public Nullable<double> tarif { get; set; }
        public string grup { get; set; }
        public Nullable<int> komp { get; set; }
        public int role { get; set; }
        public string role_name { get; set; }
        public string prod { get; set; }
        public Nullable<int> Podr_now { get; set; }
        public string p_name { get; set; }
        public Nullable<int> pod_id { get; set; }
        public int s_del { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> dt_red_start { get; set; }
    
        public virtual ICollection<Ticket> CreatedTickets { get; set; }
        public virtual ICollection<Ticket> AssignedTickets { get; set; }
        public virtual ICollection<Ticket> ChangedTickets { get; set; }
        public virtual Office Office { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<PersonalInfo> PersonalInfos { get; set; }
        public virtual Office ReferenceOffice { get; set; }
        public virtual ICollection<TicketComment> TicketComments { get; set; }
        public virtual ICollection<CalendarPeriod> CalendarPeriods { get; set; }
        public virtual ICollection<JobParticipant> JobParticipants { get; set; }
        public virtual ICollection<JobFile> Files { get; set; }
        public virtual ICollection<EditorialComment> EditorialComments { get; set; }
        public virtual ICollection<TranslatorRole> TranslatorRoles { get; set; }
        public virtual ICollection<TranslationDirection> TranslationDirections { get; set; }
        public virtual ICollection<InternalDomain> Domains { get; set; }
        public virtual CurrentStatus CurrentStatus { get; set; }
        public virtual ICollection<Ticket> tickets3 { get; set; }
        public virtual ICollection<Ticket> tickets4 { get; set; }
        public virtual ICollection<CalendarPeriod> CalenardPeriodsCreated { get; set; }
        public virtual Translator Perevod1 { get; set; }
        public virtual Translator Perevod2 { get; set; }
        public virtual ICollection<JobGrade> Grades { get; set; }
        public virtual ICollection<InternalDomain> Per_Tem1 { get; set; }
        public virtual ICollection<InternalDomain> Per_Tem2 { get; set; }
        public virtual ICollection<Domain> Temas { get; set; }
        public virtual ICollection<Domain> Temas1 { get; set; }
        public virtual ICollection<PaymentInfo> Rab_buh { get; set; }
        public virtual ICollection<PaymentInfo> Rab_buh1 { get; set; }
    }
}
