//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslatorRole
    {
        public int ID { get; set; }
        public int TranslatorID { get; set; }
        public int RoleID { get; set; }
        public string Name { get; set; }
    
        public virtual Translator Translator { get; set; }
        public virtual Role Role { get; set; }
    }
}
